// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MinimalApi_DotNet8.Data;

#nullable disable

namespace MinimalApi_DotNet8.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20231128105018_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MinimalApi_DotNet8.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "F. Scott Fitzgerald",
                            Genre = "Fiction",
                            Title = "The Great Gatsby",
                            Year = 1925
                        },
                        new
                        {
                            Id = 2,
                            Author = "John Steinbeck",
                            Genre = "Fiction",
                            Title = "The Grapes of Wrath",
                            Year = 1939
                        },
                        new
                        {
                            Id = 3,
                            Author = "George Orwell",
                            Genre = "Fiction",
                            Title = "Nineteen Eighty-Four",
                            Year = 1949
                        },
                        new
                        {
                            Id = 4,
                            Author = "James Joyce",
                            Genre = "Fiction",
                            Title = "Ulysses",
                            Year = 1922
                        },
                        new
                        {
                            Id = 5,
                            Author = "Vladimir Nabokov",
                            Genre = "Fiction",
                            Title = "Lolita",
                            Year = 1955
                        },
                        new
                        {
                            Id = 6,
                            Author = "Joseph Heller",
                            Genre = "Fiction",
                            Title = "Catch-22",
                            Year = 1961
                        },
                        new
                        {
                            Id = 7,
                            Author = "J. D. Salinger",
                            Genre = "Fiction",
                            Title = "The Catcher in the Rye",
                            Year = 1951
                        },
                        new
                        {
                            Id = 8,
                            Author = "Toni Morrison",
                            Genre = "Fiction",
                            Title = "Beloved",
                            Year = 1987
                        },
                        new
                        {
                            Id = 9,
                            Author = "William Faulkner",
                            Genre = "Fiction",
                            Title = "The Sound and the Fury",
                            Year = 1929
                        },
                        new
                        {
                            Id = 10,
                            Author = "Harper Lee",
                            Genre = "Fiction",
                            Title = "To Kill a Mockingbird",
                            Year = 1960
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
